; Script generated by Antigravity for Truva VPN & Kazık Savar

#define MyAppName "Truva VPN"
#define MyAppVersion "1.0.5.7"
#define MyAppPublisher "Truva"
#define MyAppURL "https://truvavpn.com"
#define MyAppExeName "TruvaDesktop.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D37B2A91-0C2F-4A9B-B1D6-8F2A0E4F3929}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; License agreement requirement
LicenseFile=license.txt
; Branding
OutputBaseFilename=TruvaVPN_Setup_v{#MyAppVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; Requires admin for Wintun/VPN operations
PrivilegesRequired=admin
SetupIconFile=..\Assets\truva_final_v1.ico

[Languages]
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Main application executable (Single File Bundle)
Source: "..\publish\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; Secondary dependencies (if not bundled)
Source: "..\publish\sing-box.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\publish\wintun.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\publish\WinDivert.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\publish\WinDivert64.sys"; DestDir: "{app}"; Flags: ignoreversion
; Any other assets if needed
Source: "..\Assets\*"; DestDir: "{app}\Assets"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\Resources\*"; DestDir: "{app}\Resources"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent runascurrentuser
