; Script generated by Antigravity for Truva VPN & Kazık Savar

#define MyAppName "Truva VPN"
#define MyAppVersion "1.0.8.0"
#define MyAppPublisher "Truva"
#define MyAppURL "https://truvavpn.com"
#define MyAppExeName "TruvaDesktop.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D37B2A91-0C2F-4A9B-B1D6-8F2A0E4F3929}
AppMutex=Global\TruvaVPN_SingleInstance_Mutex_D37B2A91
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; License agreement requirement
LicenseFile=license.txt
; Branding
OutputBaseFilename=TruvaVPN_Setup_v{#MyAppVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; Requires admin for Wintun/VPN operations
PrivilegesRequired=admin
SetupIconFile=..\Assets\truva_final_v1.ico
CloseApplications=yes
RestartApplications=yes

[Languages]
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Main application executable (Single File Bundle)
Source: "..\publish\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; Secondary dependencies (if not bundled)
Source: "..\publish\sing-box.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\publish\wintun.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\publish\WinDivert.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\publish\WinDivert64.sys"; DestDir: "{app}"; Flags: ignoreversion
; Any other assets if needed
Source: "..\Assets\*"; DestDir: "{app}\Assets"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\Resources\*"; DestDir: "{app}\Resources"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent runascurrentuser
; Firewall İzinleri
Filename: "netsh"; Parameters: "advfirewall firewall add rule name=""Truva VPN"" dir=in action=allow program=""{app}\{#MyAppExeName}"" enable=yes"; Flags: runhidden; StatusMsg: "Güvenlik Duvarı ayarlanıyor (Uygulama)..."
Filename: "netsh"; Parameters: "advfirewall firewall add rule name=""Truva VPN Engine"" dir=in action=allow program=""{app}\sing-box.exe"" enable=yes"; Flags: runhidden; StatusMsg: "Güvenlik Duvarı ayarlanıyor (Motor)..."
; WinDivert Driver Kaydı
Filename: "sc"; Parameters: "create WinDivert type= kernel start= demand binPath= ""{app}\WinDivert64.sys"" DisplayName= ""WinDivert 2.2"""; Flags: runhidden; StatusMsg: "Sürücü kaydediliyor (WinDivert)..."

[UninstallRun]
; Firewall İzinlerini Kaldır
Filename: "netsh"; Parameters: "advfirewall firewall delete rule name=""Truva VPN"""; Flags: runhidden
Filename: "netsh"; Parameters: "advfirewall firewall delete rule name=""Truva VPN Engine"""; Flags: runhidden
; WinDivert Sürücüsünü Kaldır
Filename: "sc"; Parameters: "delete WinDivert"; Flags: runhidden
